dist: trusty
language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install codecov coverage
script:
  - python manage.py test attero
after_success: codecov
